name 'silverlight'
maintainer 'Mike Butler'
maintainer_email 'michael.butler@progress.com'
license 'All Rights Reserved'
description 'Installs/Configures silverlight'
version '0.1.1'
chef_version '>= 17.0'
